#!/usr/bin/python
''' main program. This will handle just the parsing of options
and then it will generate a Puppet object	

if we want to get an alligator character who says 'hello world' in 
blue ink we will run it like this :

xkaasay -c alligator -a say -t 'Hello World!' -i blue '''



import os,sys,gtk
from optparse import OptionParser
import xkaa 

black = (0,0,0)
red = (255,0.0)
blue = (0,0,255)
green = (0,255,0)


parser = OptionParser()

import optparse

parser = optparse.OptionParser()
parser.add_option('-t', action="store", default="Hello World! Use -h for help", help="Your text")
parser.add_option('-a', action="store", default="say", help="action can be: say, shout, think or dream")
parser.add_option('-d', action="store", default="images/sheep.png", help="path to dream image")
parser.add_option('-c', action="store", default="snake", help="character name")
parser.add_option('-i', action="store", default=black, help="ink color")

options, args = parser.parse_args()

xkaa.Puppet(character=options.c,verb=options.a,text=options.t,dreamed=options.d,font="BonvenoCF-Light.otf",fontcolor=options.i)
gtk.main()

