#!/usr/bin/python
''' main program. This will handle just the parsing of options
and then it will generate a Puppet object	'''


import os,sys,gtk
from optparse import OptionParser
import xkaa 


parser = OptionParser()

import optparse

parser = optparse.OptionParser()
parser.add_option('-t', action="store", default="Hello World! Use -h for help")
parser.add_option('-a', action="store", default="say", help="action can be: say, shout, think or dream")
parser.add_option('-d', action="store", default="images/sheep.png", help="path to dream image")

options, args = parser.parse_args()

xkaa.Puppet(character='snake',verb=options.a,text=options.t,dreamed=options.d,font="BonvenoCF-Light.otf",fontcolor=(255,0,0))
gtk.main()

